use BookStore;
insert into Authors
	(Author)
values
	('Rick Riordan'),
	('Emily Winfield Martin'),
	('Sarah J. Maas'),
	('Cassandra Clare'),
	('Drew Daywalt and Oliver Jeffers'),
	('Ann Whitford Paul and David Walker'),
	('B. J. Novak'),
	('Angie Thomas'),
	('Andrea Beaty and David Roberts'),
	('Kelly Barnhill'),
	('R. J. Palacio'),
	('Benjamin Graham and Jason Zweig'),
	('Scott Trench'),
	('Thomas J. Stanley and William D. Danko'),
	('Andrew W. Lo'),
	('Mike Michalowicz'),
	('Jeb Blount and Mike Weinberg'),
	('Andrew Aziz'),
	('Richard Bookstaber'),
	('Brad Feld and Jason Mendelson'),
	('Sheelah Kolhatkar'),
	('John Brooks'),
	('Ric Edelman'),
	('Paul Kalanithi'),
	('Trevor Noah'),
	('Michael Finkel'),
	('Catherine Burns and Neil Gaiman'),
	('Mayte Garcia'),
	('Ariel Levy'),
	('Jason Zinoman'),
	('John A. Farrell'),
	('Lauren Graham'),
	('Bruce Springsteen'),
	('Stephan Talty'),
	('Jeff Guinn'),
	('Blizzard'),
	('BLIZZARD ENTERTAINMENT and Matt Burns'),
	('Gayle Laakmann McDowell'),
	('Ian Goodfellow and Yoshua Bengio'),
	('AurÃƒÂ©lien GÃƒÂ©ron'),
	('Prima Games'),
	('Seth Stephens-Davidowitz'),
	('Mike Meyers'),
	('Eric Matthes'),
	('Nintendo'),
	('Piggyback');
go


